language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-26

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: jDkJ5vpzfpPXlp6heL+RdONsCDy9lDsahc1R1nWlVC8ALpNiKWK/n3u8thUObVyy7g4zvn7inSNUAvozXdZi/TFIXIEsPxYKUcudkOrLx/d1Cx2Yzt114tTpFFqE+74Qiw+MMbSf8oVH+ZLvUwK0K3DusV7NdfC6DvOkkdLcAGYwMnTAEX0y1GzP/8np42zjKq2G7bO2sIxxg4PHAfjyC0e519i1Ong3D6zFBOvv0gszgBYDgAj1ib204HEV6p6vkKQMc0UzNi0TvK67rBeQJwKe69L2vOkOyvSkDK3QNcjeZ7514msFHd72be2q/QseDfs/rIUjSZ7rCKIo+3LO9HtrjSn8uSC1cNIe+65v/0+6ywH0hM8xH6vhBV1x7Yo97rZskR8FDCBa+HJD23a6h6w1dcITtinsq7R4rGRwzx1ub/secW3sve2tH+9268JDc3iSIyogDTnv/q+hsv8i5guzx/1jLcJoKVuREwj5pHnKS7zF/+sruP2RBaPMBUSPsfLpbxPlE2I+TLilvsYrZiFsb7wuCLB3RMbiNUHz143x+XBs9RzrpLZv/wcqz34cIaAaNaSpm0OlYbz3/hFRnGQ88kTqkbtnIlEGkyUDTyMOHv9dzfp67RMSyGW1oLrqgpV8vKA1cAvjxK9Zm+9esSLFS4XYzgTQ4aEJArMUJMg=
    on_success: change
