language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-26

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: acyARcR2nOZA1x+2fxCxcVXeY3eE8gg5zzRo2R65bo1QZiYiTVMMOvQAYicThLPWF/tC1xf8OGDW3Ickserbn0//SGxj+l6IGyR5tvXU5P8ARfA0ujRQrLkO+JvIv6AnnCV+Hd9+XCtpYzSrGkap1NPRyy/oAK4p4ZvWBwxp2FP2d8QS99jbWNgAB52q8f9Cdrh1+c6t2W5Vls18NdVy2OrPh8ywJqMNaT+QmYHYXPwcG/dv0EQIBnKZKFze+Esz5j15INk3WBpwb4i2MY/XiIf49CJDDxGJmn388ybQ1Q1BBNFouhKB0NgvONV+9Lqfvi+S4ILaid/jQGC765H0X9OaGjtdjoUbTlMGvr19U1yZ/fTP5wPBIkPq0hiswPZVeJbW3BMxu8iBu35QzshJAjMokUVSqFif2+SW9Mnwy2I8mNGF7VtxqfX4nMk8PYAvbafVv5l4MZJxVpXGlgWzUNxqerDbselKBPpuMdo7Ew6vqkTias7f3lioEhKlHEEs0TkAT2ML1E7BycgFjb1lMcodanutbqAMqoKjXouX4K1SnMNkxU/iOFSUxTEOG0U1PV3deN0VyJefGfvWO+GK+IvmUi//sa3/vitTYjLcuMkwj3qth+q/qo10OtkTkJ1Z76zEjHDn62DJNOUWwDCCKsmh03tD5RkAK4pDOqj1z50=
    on_success: change
