language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-26

script: ./gradlew assembleRelease

notifications:
  email: false
  slack:
    rooms:
      secure: nb2vXyQHvB46G8mrjpa6paiuFLih0M6gq+jpDFI3EgaaGMl+KMlnA1X7kjqW9SdXRDaKiCGlgKvmYzBetTINVVUe6FmAOhU939Z80qXVjoWnAUM+JrCre7WlfOm2bWvaR/LShcLP/0LKwojcZAbN27Hyw9RXu5Q2E4z1z5ofcPNtWCkr7CsOAeqjvu1o9qOXXxRFfplcvBPUfMybpYhRVPu2a8nvEBUw1WnlKvXIx95TOUnSJKSgqjSzvrOYr4Wurb6x8+dq60azUKJxkN7wc1Sa/ydjlEJfR/IV3iw6ZTKoKVHERXkDCPxA+RTfeZGBljKWvWiBjo3//PPVJkTlphDsfXgehpcwXkjveqJ+is+BPSkSfJKfP4ZY159vsGQ89a2YUcOi2sPgsD1s7cTzr/4mc28oCAU6QKEKSCDS8qTB5WSc92X9LEuL/UzOr0PSX/pBBbf4AWeG/JnyjgeEKukMy/L8I0rQa2EXuZQNbjGQdQsd99YOyDKwJ90B8N8zjyq/jVjVGT317DMehDaq6zFXRK3Cf+4qaZFK14Wi8coQt0tkijsNwCCX75TMeSkndHiXnrqESRKPawjFq2K4D7yvA63xEW1v3i1T2hWEQTAimx3mRu0XAf7sOJV8x6zqZr4Blc8QjgzVyrXSZoWxcHSEImk+xslJeWORzD5p3Aw=
    on_success: change
